### ISSUE TITLE
Panic at start up when we force node execute wasm version runtime

### ISSUE THREAD

**Issue by CaptainVincent** [second-state/substrate-wasmedge#7]
Add `--execution=Wasm` option will force node execute all substrate runtimes' wasm version.
(The default strategy is select wasm version if only it's newer than native version)

```bash
cargo run --bin node-template -- \
  --dev \
  --wasm-execution=compiledWasmedge \
  --validator \
  --execution=Wasm \
  --tmp \
  --unsafe-ws-external
```

Then you can get below error message
```
2022-08-22 17:23:18 💤 Idle (0 peers), best: #0 (0x2a73…1ce7), finalized #0 (0x2a73…1ce7), ⬇ 0 ⬆ 0

====================

Version: 4.0.0-dev-be1e431ef08

   0: sp_panic_handler::panic_hook
             at /root/substrate/substrate-wasmedge/substrate/primitives/panic-handler/src/lib.rs:166:18
   1: sp_panic_handler::set::{{closure}}
             at /root/substrate/substrate-wasmedge/substrate/primitives/panic-handler/src/lib.rs:62:12
   2: std::panicking::rust_panic_with_hook
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:702:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:588:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
   5: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   6: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   7: core::panicking::panic_display
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:72:5
   8: core::panicking::panic_str
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:56:5
   9: core::option::expect_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/option.rs:1874:5
  10: core::option::Option<T>::expect
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/option.rs:738:21
  11: wasmedge_sys::instance::function::wraper_fn_single::{{closure}}
             at /root/substrate/substrate-wasmedge/WasmEdge/bindings/rust/wasmedge-sys/src/instance/function.rs:93:23
  12: std::thread::local::LocalKey<T>::try_with
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/local.rs:445:16
  13: std::thread::local::LocalKey<T>::with
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/local.rs:421:9
  14: wasmedge_sys::instance::function::wraper_fn_single
             at /root/substrate/substrate-wasmedge/WasmEdge/bindings/rust/wasmedge-sys/src/instance/function.rs:91:5
  15: _ZN12_GLOBAL__N_112CAPIHostFunc3runEPN8WasmEdge7Runtime8Instance14MemoryInstanceEN5cxx204spanIKNS1_7VariantIJjimlfdonDv2_mDv2_lDv4_jDv4_iDv8_tDv8_sDv16_hDv16_aDv4_fDv2_dNS1_10UnknownRefENS1_7FuncRefENS1_9ExternRefEEEELm18446744073709551615EEENS7_ISM_Lm18446744073709551615EEE
  16: _ZN8WasmEdge8Executor8Executor13enterFunctionERNS_7Runtime12StackManagerERKNS2_8Instance16FunctionInstanceEPKNS_3AST11InstructionEb
  17: _ZN8WasmEdge8Executor8Executor9runCallOpERNS_7Runtime12StackManagerERKNS_3AST11InstructionERPS7_b
  18: _ZZN8WasmEdge8Executor8Executor7executeERNS_7Runtime12StackManagerEPKNS_3AST11InstructionES8_ENK3$_0clEv
  19: _ZN8WasmEdge8Executor8Executor7executeERNS_7Runtime12StackManagerEPKNS_3AST11InstructionES8_
  20: _ZN8WasmEdge8Executor8Executor11runFunctionERNS_7Runtime12StackManagerERKNS2_8Instance16FunctionInstanceEN5cxx204spanIKNS_7VariantIJjimlfdonDv2_mDv2_lDv4_jDv4_iDv8_tDv8_sDv16_hDv16_aDv4_fDv2_dNS_10UnknownRefENS_7FuncRefENS_9ExternRefEEEELm18446744073709551615EEE
  21: _ZN8WasmEdge8Executor8Executor6invokeERKNS_7Runtime8Instance16FunctionInstanceEN5cxx204spanIKNS_7VariantIJjimlfdonDv2_mDv2_lDv4_jDv4_iDv8_tDv8_sDv16_hDv16_aDv4_fDv2_dNS_10UnknownRefENS_7FuncRefENS_9ExternRefEEEELm18446744073709551615EEENS8_IKNS_7ValTypeELm18446744073709551615EEE
  22: WasmEdge_ExecutorInvoke
  23: <wasmedge_sys::executor::Executor as wasmedge_sys::Engine>::run_func
             at /root/substrate/substrate-wasmedge/WasmEdge/bindings/rust/wasmedge-sys/src/executor.rs:244:19
  24: wasmedge_sys::instance::function::Function::call
             at /root/substrate/substrate-wasmedge/WasmEdge/bindings/rust/wasmedge-sys/src/instance/function.rs:373:9
  25: sc_executor_wasmedge::instance_wrapper::InstanceWrapper::call
             at /root/substrate/substrate-wasmedge/substrate/client/executor/wasmedge/src/instance_wrapper.rs:82:5
  26: sc_executor_wasmedge::runtime::perform_call
             at /root/substrate/substrate-wasmedge/substrate/client/executor/wasmedge/src/runtime.rs:516:12
  27: sc_executor_wasmedge::runtime::WasmEdgeInstance::call_impl
             at /root/substrate/substrate-wasmedge/substrate/client/executor/wasmedge/src/runtime.rs:244:18
  28: <sc_executor_wasmedge::runtime::WasmEdgeInstance as sc_executor_common::wasm_runtime::WasmInstance>::call_with_allocation_stats
             at /root/substrate/substrate-wasmedge/substrate/client/executor/wasmedge/src/runtime.rs:271:16
  29: sc_executor_common::wasm_runtime::WasmInstance::call
             at /root/substrate/substrate-wasmedge/substrate/client/executor/common/src/wasm_runtime.rs:85:3
  30: sc_executor_common::wasm_runtime::WasmInstance::call_export
             at /root/substrate/substrate-wasmedge/substrate/client/executor/common/src/wasm_runtime.rs:105:3
  31: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call::{{closure}}::{{closure}}
             at /root/substrate/substrate-wasmedge/substrate/client/executor/src/native_executor.rs:630:8
  32: std::panicking::try::do_call
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
  33: __rust_try
  34: std::panicking::try
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
  35: std::panic::catch_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
  36: sc_executor::native_executor::with_externalities_safe::{{closure}}
             at /root/substrate/substrate-wasmedge/substrate/client/executor/src/native_executor.rs:65:3
  37: environmental::using::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.1.3/src/lib.rs:125:3
  38: std::thread::local::LocalKey<T>::try_with
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/local.rs:445:16
  39: std::thread::local::LocalKey<T>::with
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/local.rs:421:9
  40: environmental::using
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.1.3/src/lib.rs:106:2
  41: sp_externalities::scope_limited::ext::using
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.1.3/src/lib.rs:252:5
  42: sp_externalities::scope_limited::set_and_run_with_externalities
             at /root/substrate/substrate-wasmedge/substrate/primitives/externalities/src/scope_limited.rs:31:2
  43: sc_executor::native_executor::with_externalities_safe
             at /root/substrate/substrate-wasmedge/substrate/client/executor/src/native_executor.rs:61:2
  44: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call::{{closure}}
             at /root/substrate/substrate-wasmedge/substrate/client/executor/src/native_executor.rs:628:7
  45: sc_executor::native_executor::WasmExecutor<H>::with_instance::{{closure}}
             at /root/substrate/substrate-wasmedge/substrate/client/executor/src/native_executor.rs:198:5
  46: sc_executor::wasm_runtime::VersionedRuntime::with_instance
             at /root/substrate/substrate-wasmedge/substrate/client/executor/src/wasm_runtime.rs:113:18
  47: sc_executor::wasm_runtime::RuntimeCache::with_instance
             at /root/substrate/substrate-wasmedge/substrate/client/executor/src/wasm_runtime.rs:291:6
  48: sc_executor::native_executor::WasmExecutor<H>::with_instance
             at /root/substrate/substrate-wasmedge/substrate/client/executor/src/native_executor.rs:188:9
  49: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call
             at /root/substrate/substrate-wasmedge/substrate/client/executor/src/native_executor.rs:606:16
  50: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_aux
             at /root/substrate/substrate-wasmedge/substrate/primitives/state-machine/src/lib.rs:428:31
  51: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_using_consensus_failure_handler
             at /root/substrate/substrate-wasmedge/substrate/primitives/state-machine/src/lib.rs:544:7
  52: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
             at /root/substrate/substrate-wasmedge/substrate/client/service/src/client/call_executor.rs:267:5
  53: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
             at /root/substrate/substrate-wasmedge/substrate/client/service/src/client/client.rs:1674:3
  54: <node_template_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_consensus_aura::AuraApi<__SR_API_BLOCK__,sp_consensus_aura::sr25519::app_sr25519::Public>>::__runtime_api_internal_call_api_at::{{closure}}
             at runtime/src/lib.rs:339:1
  55: <node_template_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_consensus_aura::AuraApi<__SR_API_BLOCK__,sp_consensus_aura::sr25519::app_sr25519::Public>>::__runtime_api_internal_call_api_at
             at runtime/src/lib.rs:339:1
  56: sp_consensus_aura::AuraApi::authorities
             at /root/substrate/substrate-wasmedge/substrate/primitives/consensus/aura/src/lib.rs:84:1
  57: sc_consensus_aura::authorities
             at /root/substrate/substrate-wasmedge/substrate/client/consensus/aura/src/lib.rs:552:2
  58: <sc_consensus_aura::AuraWorker<C,E,I,P,SO,L,BS> as sc_consensus_slots::SimpleSlotWorker<B>>::epoch_data
             at /root/substrate/substrate-wasmedge/substrate/client/consensus/aura/src/lib.rs:355:3
  59: sc_consensus_slots::SimpleSlotWorker::on_slot::{{closure}}
             at /root/substrate/substrate-wasmedge/substrate/client/consensus/slots/src/lib.rs:275:26
  60: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  61: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/future.rs:124:9
  62: <sc_consensus_slots::SimpleSlotWorkerToSlotWorker<T> as sc_consensus_slots::SlotWorker<B,<<T as sc_consensus_slots::SimpleSlotWorker<B>>::Proposer as sp_consensus::Proposer<B>>::Proof>>::on_slot::{{closure}}
             at /root/substrate/substrate-wasmedge/substrate/client/consensus/slots/src/lib.rs:440:28
  63: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  64: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/future.rs:124:9
  65: sc_consensus_slots::start_slot_worker::{{closure}}
             at /root/substrate/substrate-wasmedge/substrate/client/consensus/slots/src/lib.rs:532:37
  66: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  67: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panic/unwind_safe.rs:296:9
  68: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/future/future/catch_unwind.rs:36:42
  69: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panic/unwind_safe.rs:271:9
  70: std::panicking::try::do_call
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
  71: __rust_try
  72: std::panicking::try
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
  73: std::panic::catch_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
  74: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/future/future/catch_unwind.rs:36:9
  75: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/future/future/map.rs:55:37
  76: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/lib.rs:91:13
  77: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
             at /root/substrate/substrate-wasmedge/substrate/client/service/src/task_manager/prometheus_future.rs:61:3
  78: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panic/unwind_safe.rs:296:9
  79: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/future/future/catch_unwind.rs:36:42
  80: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panic/unwind_safe.rs:271:9
  81: std::panicking::try::do_call
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
  82: __rust_try
  83: std::panicking::try
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
  84: std::panic::catch_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
  85: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/future/future/catch_unwind.rs:36:9
  86: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/future.rs:124:9
  87: futures_util::future::future::FutureExt::poll_unpin
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/future/future/mod.rs:562:9
  88: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/future/select.rs:108:35
  89: sc_service::task_manager::SpawnTaskHandle::spawn_inner::{{closure}}
             at /root/substrate/substrate-wasmedge/substrate/client/service/src/task_manager/mod.rs:145:32
  90: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  91: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-futures-0.2.5/src/lib.rs:283:9
  92: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/park/thread.rs:263:54
  93: tokio::coop::with_budget::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:102:9
  94: std::thread::local::LocalKey<T>::try_with
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/local.rs:445:16
  95: std::thread::local::LocalKey<T>::with
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/local.rs:421:9
  96: tokio::coop::with_budget
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:95:5
      tokio::coop::budget
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:72:5
      tokio::park::thread::CachedParkThread::block_on
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/park/thread.rs:263:31
  97: tokio::runtime::enter::Enter::block_on
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/enter.rs:152:13
  98: tokio::runtime::handle::Handle::block_on
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/handle.rs:297:9
  99: sc_service::task_manager::SpawnTaskHandle::spawn_inner::{{closure}}
             at /root/substrate/substrate-wasmedge/substrate/client/service/src/task_manager/mod.rs:172:6
 100: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1951:9
 101: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/blocking/task.rs:42:21
 102: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/core.rs:165:17
 103: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/loom/std/unsafe_cell.rs:14:9
 104: tokio::runtime::task::core::CoreStage<T>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/core.rs:155:13
 105: tokio::runtime::task::harness::poll_future::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:480:19
 106: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panic/unwind_safe.rs:271:9
 107: std::panicking::try::do_call
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
 108: __rust_try
 109: std::panicking::try
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
 110: std::panic::catch_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
 111: tokio::runtime::task::harness::poll_future
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:468:18
 112: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:104:27
 113: tokio::runtime::task::harness::Harness<T,S>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:57:15
 114: tokio::runtime::task::raw::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/raw.rs:144:5
 115: tokio::runtime::task::raw::RawTask::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/raw.rs:84:18
 116: tokio::runtime::task::UnownedTask<S>::run
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/mod.rs:418:9
 117: tokio::runtime::blocking::pool::Task::run
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/blocking/pool.rs:91:9
 118: tokio::runtime::blocking::pool::Inner::run
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/blocking/pool.rs:325:17
 119: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/blocking/pool.rs:300:13
 120: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:122:18
 121: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/mod.rs:505:17
 122: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panic/unwind_safe.rs:271:9
 123: std::panicking::try::do_call
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
 124: __rust_try
 125: std::panicking::try
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
 126: std::panic::catch_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
 127: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/mod.rs:504:30
 128: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
 129: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1951:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1951:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys/unix/thread.rs:108:17
 130: start_thread
 131: clone


Thread 'tokio-runtime-worker' panicked at 'host function should be there', /root/substrate/substrate-wasmedge/WasmEdge/bindings/rust/wasmedge-sys/src/instance/function.rs:95

This is a bug. Please report it at:

	support.anonymous.an

Segmentation fault (core dumped)
```

**Comment by EmisonLu** [comment]
Thanks a lot for this bug report! It was fixed in [commit e7f5f](https://github.com/second-state/substrate-wasmedge/commit/e7f5f3492c0e258e38da20e88ce10ee59fa74188).

The reason for this bug is that the host function was previously created in single-thread and did not take into account the multi-thread case.

However, in some cases, [HOST_FUNCS](https://github.com/WasmEdge/WasmEdge/blob/master/bindings/rust/wasmedge-sys/src/lib.rs#L227) in the rust SDK may cause a deadlock, which we are working on fixing.

**Comment by CaptainVincent** [comment]
Verify done. All operations basically seem good.

Check below items.
- [x] make sure call flow walk through Wasmedge
- [x] regular produce block
- [x] balance transfer between exist accounts
- [x] sudo set_code upgrade runtime (upload wasm file)
